### ISSUE TITLE
[unified] Page unresponsive: “ You can wait for it to become responsive or exit the page.”

### ISSUE THREAD

**Issue by HelloYes1** [ungoogled-software/ungoogled-chromium-debian#266] opened 2021-11-26 17:28 UTC
Other browsers work (Firefox, Brave, Edge) and also Chromium. Tried Chromium today.

Ungoogled Chromium does not work for me. Most sites start to hang within seconds.
"chrome://flags/#extension-mime-request-handling" hangs within a second. 

Installed it from here (multiple times now):
http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Impish/
Following these steps (with a reference to the Impish folder):
https://askubuntu.com/questions/1298493/how-to-install-ungoogled-chromiun-on-ubuntu-20-04

Ubuntu 21.10

**Comment by markozajc** [comment] 2021-11-26 19:56
Likely a duplicate of #247.
The current workaround is to use the unportable version by Eloston at https://github.com/Eloston/ungoogled-chromium-binaries (the prebuilt binaries seem to be built for Debian Bullseye, so you might have to build it yourself if they don't work on your system).

**Comment by HelloYes1** [comment] 2021-11-26 21:12
Could surely be, an extension like uBlock almost stops everything in my browser.
I don't want to be unthankful, but I think it ends here for me. Sadly I would not even know where to start or how to obtain sufficient knowledge to get started. Ubuntu is on my PC now for 2 weeks. Please let me know if I can test something. Or if there's some sort of information on how to get things like this done (for a total noob). Thank you!

**Comment by markozajc** [comment] 2021-11-26 21:44
Create a new directory (call it whatever you want), and download the following files into it:
- [ungoogled-chromium-common](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-common_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium-driver](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-driver_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium-sandbox](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-sandbox_95.0.4638.69-1.unportable1_amd64.deb)
- [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium_95.0.4638.69-1.unportable1_amd64.deb)

Then open up a terminal, cd into the directory you created, and install the deb files with `sudo apt install ./*.deb`. If this fails, or if ungoogled chromium doesn't work afterwards, you'll have to compile it yourself (I haven't yet tried building the unportable branch, but you might be able to get help from Eloston).

**Comment by HelloYes1** [comment] 2021-11-26 22:15
Wow, this is great!
I did as you described. Download of the files and install and it's working correctly as far as I see. Things that didn't work before do work now. Thats for sure. 

The uBlock extension is also working 

Placed this message with the ungoogled chromium browser.
"Version 95.0.4638.69 (Official Build, ungoogled-chromium) built on Debian bullseye/11, running on Ubuntu impish/21.10 (64-bit)" 

Thanks a lot Marko!

**Comment by RegalCucks** [comment] 2021-12-07 01:35
Having the same issue, using Mint (Ubuntu Focal) and after being unable to manually download extensions via crxextractor.com (file never completes download), I tried going to Chrome://Flags to change the extensions setting and get the same "unresponsive" message and the whole browser has to be restarted 4-5 times before it works again.

**Comment by Eloston** [comment] 2021-12-15 06:47
Yeah the workaround is to use unportable for now. I am keeping it updated.

**Comment by freduard** [comment] 2021-12-23 21:28
Also experiencing the same issue.

Kubuntu 21.10, Impish install. Unportable is working as expected but I'm really looking forward to a better solution.

**Comment by ghost** [comment] 2023-03-21 10:42
This appears to be fixed in latest release.

**Closed as completed by ghost** 2023-03-21 10:42 UTC
