### ISSUE TITLE
WebGL seems broken after the latest update via apt repos

### ISSUE THREAD

**Issue by datengraben** [ungoogled-software/ungoogled-chromium-debian#353] opened 2024-12-17 14:37 UTC
Sorry if this is a bit uninformed. But after the latest update via apt I have trouble using several sites,  that use webgl (figma/several map apps that use webgl).

Also, may be connected to the issue above: If I start my browser it will restart my latest session (loads existing tab windows). The window that is active, is in loading state, but no content will be displayed. After several seconds CPU will spike from idle to ~30/40% of utilitization. I have to close and re-open the active tab of each window to get the CPU down to idle state and the windows to diplay the content of the URL.

I'm unsure if the two issues are related. How can I troubleshoot? Can I provide any information thats helpful to determine whether this issue is fixable on ungoogled-chromium end?

Should I update any linux webgl driver? Appreciate any hint.

**Comment by iskunk** [comment] 2024-12-17 19:49
Hello @datengraben,

I assume that things were working with 131.0.6778.108, and that you're seeing breakage with 131.0.6778.139.

The latter version has a significant change under the hood: Debian switched to using the GNU C++ runtime (libstdc++), away from the LLVM C++ runtime (libc++). Chromium is mostly C++, so this change affects basically the entire stack, and could very well lead to the issues you're seeing.

I take it you were loading WebGL sites with a proper GPU? What hardware/driver are you using there? Also: Xorg or Wayland? Do WebGL sites load correctly in Firefox?

Diagnosing the issue is going to be tricky. There are a few things I'd suggest trying:

* Run ungoogled-chromium in a terminal, and watch for any unusual error messages when you load a WebGL site. (Also try this during the initial reloading of the previous session, though I'm less confident that will provide a smoking gun.)

* Boot an Ubuntu live image on your system, install OpenGL/WebGL drivers as applicable, and see if ungoogled-chromium fails in the same way. This would help rule out any issue with your system configuration. If you would like to try the previous version to confirm that it works, you can still download it from [here](https://launchpad.net/~xtradeb/+archive/ubuntu/apps/+files/chromium_131.0.6778.108-1xtradeb1.2204.1_amd64.deb) (edit the URL as appropriate).

* Boot a _Debian_ live image on your system, install OpenGL/WebGL drivers, and download the previous version of `chromium` (Debian build, not XtraDeb's) from https://snapshot.debian.org/ . See if that can be made to load the WebGL sites correctly. Then, install the current version of `chromium`. If that breaks in the same way, then you have a bug that can be reported directly to Debian. This is the best-case scenario for getting it addressed.

  (You might try copying over your `~/.config/chromium/` tree to see if you can reproduce the initial-reload issue, but of course that would have privacy implications running on a non-ungoogled version of Chromium.)

* Maybe try updating your WebGL driver to see if that affects anything. However, I'd hesitate to do this if you can't easily return to the original version, since that one is known to work and the newer one is a question mark.

**Comment by datengraben** [comment] 2024-12-18 14:38
Hi Daniel,

thanks for the help/pointers!

> I assume that things were working with 131.0.6778.108, and that you're seeing breakage with 131.0.6778.139.

I don't know which one I had before. But the recent version is: `Version 131.0.6778.139 (Official Build, ungoogled-chromium) (64-Bit)`

> I take it you were loading WebGL sites with a proper GPU? What hardware/driver are you using there?

```
❯ lspci -k | grep -EA3 'VGA|3D|Display'
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev d1)
	Subsystem: Lenovo Cezanne
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

> Also: Xorg or Wayland? Do WebGL sites load correctly in Firefox?

Yes without issues.

> * Run ungoogled-chromium in a terminal, and watch for any unusual error messages when you load a WebGL site. (Also try this during the initial reloading of the previous session, though I'm less confident that will provide a smoking gun.)

I just realized that I've set up the app via flatpak and not the apt repos. Sorry for that, I can move this issue to the appropriate repo.

But anyway here are the logs of the cli start.

```
❯ flatpak run io.github.ungoogled_software.ungoogled_chromium --proxy-server=127.0.0.1:8888

(process:2): Gtk-WARNING **: 15:31:24.565: Locale not supported by C library.
	Using the fallback 'C' locale.
[33:33:1218/153124.773713:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[33:33:1218/153124.773834:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[33:33:1218/153124.773867:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[33:33:1218/153124.774036:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[33:33:1218/153124.774078:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[33:33:1218/153124.774108:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[33:33:1218/153124.774136:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[33:33:1218/153124.774167:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[33:33:1218/153124.774836:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[33:33:1218/153124.774881:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[33:33:1218/153124.774911:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[33:33:1218/153124.775058:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[33:33:1218/153124.775091:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[33:33:1218/153124.775119:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[33:33:1218/153124.775145:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[33:33:1218/153124.775171:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[33:33:1218/153124.776148:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
[80:80:1218/153124.885283:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[80:80:1218/153124.885400:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[80:80:1218/153124.885437:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[80:80:1218/153124.885623:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[80:80:1218/153124.885671:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[80:80:1218/153124.885707:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[80:80:1218/153124.885744:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[80:80:1218/153124.885785:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[80:80:1218/153124.886614:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[80:80:1218/153124.886669:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[80:80:1218/153124.886706:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[80:80:1218/153124.886865:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[80:80:1218/153124.886913:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[80:80:1218/153124.886946:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[80:80:1218/153124.886980:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[80:80:1218/153124.887013:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[80:80:1218/153124.888093:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
[2:2:1218/153124.982036:ERROR:atom_cache.cc(229)] Add WM_CHANGE_STATE to kAtomsToCache
[224:224:1218/153125.648095:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[224:224:1218/153125.648209:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[224:224:1218/153125.648256:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[224:224:1218/153125.648437:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[224:224:1218/153125.648484:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[224:224:1218/153125.648516:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[224:224:1218/153125.648546:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[224:224:1218/153125.648577:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[224:224:1218/153125.649338:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[224:224:1218/153125.649390:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[224:224:1218/153125.649424:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[224:224:1218/153125.649574:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[224:224:1218/153125.649609:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[224:224:1218/153125.649636:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[224:224:1218/153125.649663:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[224:224:1218/153125.649688:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[224:224:1218/153125.650857:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
[231:231:1218/153125.757701:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[231:231:1218/153125.757796:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[231:231:1218/153125.757836:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[231:231:1218/153125.758009:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[231:231:1218/153125.758055:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[231:231:1218/153125.758085:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[231:231:1218/153125.758114:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[231:231:1218/153125.758163:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[231:231:1218/153125.759038:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[231:231:1218/153125.759102:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[231:231:1218/153125.759142:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[231:231:1218/153125.759327:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[231:231:1218/153125.759377:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[231:231:1218/153125.759410:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[231:231:1218/153125.759443:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[231:231:1218/153125.759476:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[231:231:1218/153125.760867:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
[238:238:1218/153125.858845:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[238:238:1218/153125.858975:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[238:238:1218/153125.859021:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[238:238:1218/153125.859242:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[238:238:1218/153125.859302:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[238:238:1218/153125.859346:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[238:238:1218/153125.859383:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[238:238:1218/153125.859422:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[238:238:1218/153125.860480:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[238:238:1218/153125.860539:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[238:238:1218/153125.860582:ERROR:gl_display.cc(767)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[238:238:1218/153125.860773:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
[238:238:1218/153125.860818:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
[238:238:1218/153125.860854:ERROR:gl_display.cc(767)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[238:238:1218/153125.860897:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[238:238:1218/153125.860939:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[238:238:1218/153125.862280:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
[245:245:1218/153125.882121:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
[245:245:1218/153125.882213:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
[245:245:1218/153125.882266:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
[245:245:1218/153125.882316:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
[245:245:1218/153125.882355:ERROR:gl_display.cc(767)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[245:245:1218/153125.882393:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[245:245:1218/153125.882431:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[245:245:1218/153125.883328:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface
[245:245:1218/153125.883372:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_xcb_surface
[245:245:1218/153125.883421:ERROR:angle_platform_impl.cc(44)] Display.cpp:1062 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
ERR: Display.cpp:1062 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
[245:245:1218/153125.883461:ERROR:gl_display.cc(497)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2024.
[245:245:1218/153125.883494:ERROR:gl_display.cc(767)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[245:245:1218/153125.883524:ERROR:gl_display.cc(801)] Initialization of all EGL display types failed.
[245:245:1218/153125.883554:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[245:245:1218/153125.884927:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open dri: /usr/lib/x86_64-linux-gnu/GL/lib/gbm/dri_gbm.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/lib/gbm, suffix _gbm)
[2:15:1218/153126.036154:ERROR:ev_root_ca_metadata.cc(162)] Failed to decode OID: 0
```

Am Tue, Dec 17, 2024 at 11:49:50AM -0800 schrieb Daniel Richard G.:

**Comment by iskunk** [comment] 2024-12-19 03:51
> I just realized that I've set up the app via flatpak and not the apt repos. Sorry for that, I can move this issue to the appropriate repo.

Yeah, Flatpak is a whoooole 'nuther can of worms :-]  Be sure to mention to them that Firefox is handling WebGL correctly; that is a good reference point.

> But anyway here are the logs of the cli start.

Looking through that log, I suspect you may want to give Chromium's `--use-gl` flag a try. For example, pass in `--use-gl=egl`. You can find this and other Chromium command-line options documented [here](https://peter.sh/experiments/chromium-command-line-switches/). Beyond that, it could well be Flatpak interfering with the GPU driver in some way.

Closing this issue, as there's not much more I can offer. Hope you find a solution...

**Closed as not planned by iskunk** 2024-12-19 03:51 UTC
