### ISSUE TITLE
The instructions to add the OBS signing key break the ability to add PPA's on Mint 19.x and Mint 20.

### ISSUE THREAD

**Issue by smurphos** [ungoogled-software/ungoogled-chromium-debian#153] opened 2020-06-28 04:53 UTC
Hi,

https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium

This line `sudo wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Focal/Release.key -O "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc"` does not correctly add the key and on subsequently trying to add PPA to the sources the partially installed ungoogled_chromium key causes failure to import the PPA signing key.

```
steve@steve-VirtualBox:~$ sudo wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Focal/Release.key -O "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc"
2020-06-28 05:22:11 URL:https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key [1126/1126] -> "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc" [1]
steve@steve-VirtualBox:~$ apt update
Hit:1 http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                
Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease               
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease    
Ign:10 http://packages.linuxmint.com ulyana InRelease
Hit:11 http://archive.canonical.com/ubuntu focal InRelease
Hit:12 http://packages.linuxmint.com ulyana Release
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
steve@steve-VirtualBox:~$ sudo add-apt-repository ppa:phoerious/keepassxc
You are about to add the following PPA:
 KeePassXC Password Manager (official upstream PPA)

https://keepassxc.org/download/
 More info: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/apt-key-gpghome.96c7RW0TWW/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys D89C66D0E31FEA2874EBD20561922AB60068FCD6
gpg: key 61922AB60068FCD6: public key "Launchpad PPA for Janek Bevendorff" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: invalid key resource URL '/tmp/apt-key-gpghome.96c7RW0TWW/home:ungoogled_chromium.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
gpg: key 02456C79B2FD48BF: 1 signature not checked due to a missing key
gpg: key A6616109451BBBF2: 12 signatures not checked due to missing keys
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key C8CAB6595FDFF622: 2 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 8
gpg:       skipped new keys: 8
steve@steve-VirtualBox:~$ apt update
[sudo] password for steve:               
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                
Get:3 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal InRelease [18.0 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease                         
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease                 
Hit:6 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease               
Hit:8 http://archive.canonical.com/ubuntu focal InRelease                      
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:10 http://security.ubuntu.com/ubuntu focal-security InRelease              
Ign:11 http://packages.linuxmint.com ulyana InRelease                          
Hit:12 http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease
Hit:13 http://packages.linuxmint.com ulyana Release
Err:3 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 61922AB60068FCD6
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 61922AB60068FCD6
E: The repository 'http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

The solution - on adding the ungoogled-chromium repo the key can be correctly added with this alternative command

Focal / Mint 20
`wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Focal/Release.key -O /tmp/home:ungoogled_chromium.asc; sudo apt-key add /tmp/home:ungoogled_chromium.asc`

Bionic / Mint 19.x
`wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Bionic/Release.key -O /tmp/home:ungoogled_chromium.asc; sudo apt-key add /tmp/home:ungoogled_chromium.asc`

Please consider updating the instructions at https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium

Cheers

**Comment by smurphos** [comment] 2020-06-28 05:28
Hi, on checking this issue on a default Ubuntu install it appears the issue caused by the current instructions is Mint specific.

**Comment by mpaunovic** [comment] 2020-06-29 12:52
I'm using Linux Mint 19.3 and I can confirm the issue. smurphos' fix works.

**Comment by Eloston** [comment] 2020-06-29 19:55
Duplicate of https://github.com/Eloston/ungoogled-chromium/issues/1071. A new command was proposed upstream in https://github.com/openSUSE/software-o-o/pull/812.

**Closed as completed by Eloston** 2020-06-29 19:55 UTC
Labels: duplicate
