### ISSUE TITLE
extensions and downloads don't work

### ISSUE THREAD

**Issue by Kwaskoff** [ungoogled-software/ungoogled-chromium-debian#261] opened 2021-11-10 10:06 UTC
I have build by myself Version 95.0.4638.69 (Official Build, ungoogled-chromium) Ubuntu 21.10 (64-bit)
And it have troubles with extensions and downloads
I switched to developer mode and load unpacked extensions
I tested uBlock - it didn't open
I tested Metamask - it didn't open and had errors, when I wanted to open errors - it was frozen 
![Screenshot from 2021-11-10 12-43-46](https://user-images.githubusercontent.com/15308024/141090111-03ce358d-229b-415b-8241-a9bf05d8315d.png)
When I downloaded the files, it disappeared

**Comment by markozajc** [comment] 2021-11-10 11:54
Likely related to #247.
The workaround for now is to use Eloston's unportable builds, which don't have this issue: https://github.com/Eloston/ungoogled-chromium-binaries/releases

**Comment by Kwaskoff** [comment] 2021-11-10 19:56
> Likely related to #247. The workaround for now is to use Eloston's unportable builds, which don't have this issue: https://github.com/Eloston/ungoogled-chromium-binaries/releases

@markozajc do you know which different? Eloston made fork..

**Comment by markozajc** [comment] 2021-11-10 21:09
Read #255.

**Comment by Eloston** [comment] 2021-12-15 06:39
Duplicate of #245

**Closed as completed by Eloston** 2021-12-15 06:39 UTC
Labels: duplicate
