### ISSUE TITLE
[unified] Installing one extension makes ungoogle-chromium stop woking! 

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [ungoogled-software/ungoogled-chromium-debian#265] opened 2021-11-24 09:23 UTC
Try to install ublock. Open new tab search google.com it just the page just keep loading! 

I use Ubuntu focal
Version 95.0.4638.54

**Comment by markozajc** [comment] 2021-11-24 13:47
Likely a duplicate of #247.
The current workaround is to use the unportable version by Eloston at `https://github.com/Eloston/ungoogled-chromium-binaries/releases`.

**Comment by GarikTester** [comment] 2021-11-24 15:27
> Likely a duplicate of #247. The current workaround is to use the unportable version by Eloston at `https://github.com/Eloston/ungoogled-chromium-binaries/releases`.

Will Eloston's unportable build work on 2600k Sandy Bridge with that -march-skylake option?
Will it be necessary to reconfigure (or re-create) the profile when switching to unified build by @braewoods, when it will be polished enough?

**Comment by markozajc** [comment] 2021-11-24 15:30
> Will Eloston's unportable build work on 2600k Sandy Bridge with that -march-skylake option?

Unsure, try running it to find out. You can build it yourself with the correct configuration or open an issue on that repository to add support for it in case it doesn't work.
> Will it be necessary to reconfigure (or re-create) the profile when switching to unified build by @braewoods, when it will be polished enough?

No, as long as the Chromium version of the unified build is equal or higher to the unportable one when you run it (though it doesn't hurt to make a backup either way).

**Comment by Eloston** [comment] 2021-12-15 06:45
> Will Eloston's unportable build work on 2600k Sandy Bridge with that -march-skylake option?

The latest 96 version builds with `corei7-avx` which might work with Sandy Bridge. I may continue to build with this CPU feature set instead since I also have some older machines I want to keep updated.

> No, as long as the Chromium version of the unified build is equal or higher to the unportable one when you run it 

This is correct!

Closing since the OP found a workaround.

**Closed as completed by Eloston** 2021-12-15 06:45 UTC
