### ISSUE TITLE
GPG Keys are broken: "The following signatures were invalid: EXPKEYSIG"

### ISSUE THREAD

**Issue by ProgrammingLife** [ungoogled-software/ungoogled-chromium-debian#311] opened 2022-11-30 08:20 UTC
```
$  curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key'
                                                                    
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.15 (GNU/Linux)

mQENBF6ihdcBCADgXNBknkAv8IvFAY/iLbzll7RGPwfljtebtjO+5FTZDS5TAuxR
y/Q+82UY47wjzMNq6wpOEsrlYjTe3CuOWnh7lvdOXWaDeoeLUs8puC0wGvZV2hxO
gLvqnbgDhMx/ePMh8+AcfYvmzlaAFyyFHPZ5/UWEONS49aX01aXekT0jLzUvhEHW
QJvYG+KZn1/uhf9WV5kL2AbISH2LRq9YGc3QGi1SpiRthiAsiY8sNPCiTIOlIJmP
xFqaE5pk1qZ98T+yEglxrZBV/sWnWBBwR+PMRJUEISLJip/e3TYJiLBMgfOteASO
E4vVnKibYe1XLyGLy9Bdb2Iiq2PD0jXzzlwhABEBAAG0UGhvbWU6dW5nb29nbGVk
X2Nocm9taXVtIE9CUyBQcm9qZWN0IDxob21lOnVuZ29vZ2xlZF9jaHJvbWl1bUBi
dWlsZC5vcGVuc3VzZS5vcmc+iQE+BBMBCAAoBQJeooXXAhsDBQkEHrAABgsJCAcD
AgYVCAIJCgsEFgIDAQIeAQIXgAAKCRACRWx5sv1Iv8QcB/9oTSZSK2M3CnKEeFaR
6m0WKYOoQLZAQOY77BH8qPJ2hh4iZuBjX0IB2k2HeEmyYLY6CnBaTr6QCX1dYZ5i
tUXEAvjM7KS44QtXpl+5MLdJiuMk7iD/n8aLvzkvKuO+F4k2bV4daQ5ZJTbN6uSL
F+3RJssrAaE8Y7QWMRsRQUK5sXJge18evSUSKHmk6XX93iprYhkPiN0Zq5LK5vZw
OgJz9TKioe7jTZKHE9eNV4JV6nxVGBf3LaCoWKNSxliB1rkukQZY829UyRMlztmQ
cAn8PzAYCuy/RGEmGOZTbEpYCpJ4MczzTGID3xy1ZvU4aEmd5D5PHaPj29LfiMgK
ykNqiEYEExECAAYFAl6ihdcACgkQOzARt2udZSPioACgnF7A13NWVZe7OE6IV7xl
c1PXneAAn2Qe/pFB41wWFHkL0bj2MeP8Lywi
=ioNL
-----END PGP PUBLIC KEY BLOCK-----

$ curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal/Release.key' | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg > /dev/null

$ apt update
...
Err:14 http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease                                                                                                                  
  The following signatures were invalid: EXPKEYSIG 02456C79B2FD48BF home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>
...
W: GPG error: http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease: The following signatures were invalid: EXPKEYSIG 02456C79B2FD48BF home:ungoogled_chromium OBS Project <home:ungoogled_chromium@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease' is not signed.
```

**Comment by networkException** [comment] 2022-11-30 08:28
Duplicate of #307

**Closed as not planned by networkException** 2022-11-30 08:28 UTC
