### ISSUE TITLE
Ungoogled Chromium 98 doesn't open in Debian 11

### ISSUE THREAD

**Issue by JManiaGitHub** [ungoogled-software/ungoogled-chromium-debian#286] opened 2022-02-28 21:35 UTC
Hello, some days ago i downloaded Ungoogled Chromium for android, wich was good, then i downloaded it for my computer wich runs Debian 11 

terminal view of system:
Linux computer 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

so, i downloaded the 2 deb files (ungoogled chromium and ungoogled chromium common)
and installed as shown in the install intructions, installation completed and i tried to open the newly installed browser...
but it did not open, i tried again and again, than, i tried running it via terminal, via normal user, as sudo, and as root too, but
nothing helped, the terminal returns me "illegal instruction" every time i do that, whats the problem here?

**Comment by ghost** [comment] 2022-03-02 00:28
It probably means your CPU isn't new enough for Chromium to function.

**Comment by punkmumrik** [comment] 2022-03-02 23:48
don't know it this will fix your problem, but i had to install **libjsoncpp24_1.9.4-4_amd64.deb** for it to work, even though i had libjsoncpp25_1.9.5-3 installed.

**Comment by ernobe** [comment] 2022-05-25 15:12
Did you try to install Ungoogled Chromium for Android on your computer OS?

> It probably means your CPU isn't new enough for Chromium to function.

Or his OS is 32 bit.

**Comment by ghost** [comment] 2023-03-24 08:38
Closing this. Nothing we do will fix this because the issue is Chromium requiring newer x86 instructions than their hardware provides.

**Closed as completed by ghost** 2023-03-24 08:38 UTC
